MEDIA = linux

# enable valgrind
CFLAGS		+= -UNVALGRIND

INCDIRS		+= arch/x86/include/linux
SRCDIRS		+= arch/x86/core/linux

$(BIN)/%.linux : $(BIN)/%.linux.tmp
	$(QM)$(ECHO) "  [FINISH] $@"
	$(Q)cp -p $< $@
